exciting-kfs/kfs

src/main.rs
src/stack.rs
src/tty.rs
src/tty/controller.rs
src/tty/keyboard.rs
src/tty/screen.rs
src/tty/screen_char.rs
src/tty/tty.rs

- tty 버퍼 리펙토링.
- 순환 버퍼 기능.(buffer_top)

refactor: change tty buffer type from char[][] to ScreenChar[][]

---

src/console.rs
src/console/console.rs
src/console/console_manager.rs
src/console/cursor.rs
src/console/key_record.rs
src/console/readonly_console.rs
src/driver/vga/text_vga.rs
src/driver/vga/text_vga/attr.rs
src/driver/vga/text_vga/screen_char.rs
src/input/key_event.rs
src/input/keyboard.rs
src/main.rs
src/printk.rs
src/printk/printk.rs

feature: printk ,fix: circular console buffer

---

src/backtrace.rs
src/backtrace/strtab.rs
src/main.rs

fix: remove expect, unwrap in backtrace logic

---

Makefile
scripts/qemu.sh
src/console/console_manager.rs
src/driver.rs
src/driver/serial.rs
src/main.rs
src/printk/printk.rs
src/subroutine/dmesg.rs

* Printk의 결과물이 시리얼 포트를 통해 전달됨.
* serial COM1 port + Qemu named pipe backend
* make dmesg로 호스트 컴퓨터에서 출력 확인 가능.

Serial Printk 

---

Cargo.lock
Cargo.toml
Makefile
kfs_macro/Cargo.toml
kfs_macro/src/lib.rs
scripts/qemu.sh
scripts/serial.sh
scripts/test.sh
src/backtrace.rs
src/boot.rs
src/boot/strtab.rs
src/boot/symtab.rs
src/driver/serial.rs
src/lib.rs
src/printk/printk.rs
src/subroutine/dmesg.rs
src/subroutine/shell.rs

Please see **related issues** if you need explanations for this PR.
**related issue**: close #31 
* Refactor `mod serial`: Only COM1 -> COM1, COM2 
* Read command from the host with serial(COM2) and Write it to shell
* Extract `symtab, strtab` from `mod backtrace` to `mod boot`
* Add iterators for `symtab, strtab`
* Implement shell command `unit_test`
* Prevent dropping test function by linker.
* Add attribute-macro `kernel_test` for unit test

Enabling test

---

scripts/qemu.sh
src/subroutine/shell.rs

[BUG FIX] make run시 무한루프에 빠짐.

---

src/mm/cache_allocator/cache_manager.rs
src/mm/cache_allocator/size_cache.rs
src/mm/cache_allocator/traits.rs
src/mm/kmalloc.rs

feat: ksize

---

Makefile
linker-script/kernel.ld
src/lib.rs
src/mm.rs
src/mm/cache_allocator.rs
src/mm/cache_allocator/meta_cache.rs
src/mm/cache_allocator/util.rs
src/mm/constant.rs
src/mm/kmalloc.rs
src/mm/meta_page.rs
src/mm/page_allocator.rs
src/mm/page_allocator/buddy_allocator.rs
src/mm/page_allocator/free_list.rs
src/mm/page_allocator/util.rs
src/mm/util.rs
src/mm/virtual_allocator.rs
src/mm/virtual_allocator/vmalloc.rs
src/mm/x86/init.rs
src/mm/x86/x86_page.rs

Changes:
MetaPage
* new field: mapped_addr
* reduce metadata size with bitflag
PageAllocator
* separate ZONE_HIGH into 2 part
PD
* map / unmap functions

Implement Virtual Memory Allocator

---

scripts/qemu.sh
src/asm/init/paging.S
src/boot.rs
src/lib.rs
src/mm.rs
src/mm/alloc/page/buddy_allocator.rs
src/mm/alloc/page/free_list.rs
src/mm/alloc/page/page_allocator.rs
src/mm/alloc/virt/virtual_allocator.rs
src/mm/page.rs
src/mm/page/arch/init.rs
src/mm/page/os/metadata.rs
src/mm/page/os/page.rs
src/mm/page/os/table.rs

- refactor vmemory init
- fix buddy allocator

Refactor vmemory init & fix buddy allocator

---

.cargo/config.toml
Makefile
kfs_macro/src/lib.rs
src/lib.rs
src/util/arch/cpuid.rs

Now, we can classify tests!
Before this pr, we should run all uninterested and interested tests at once.
It is so boring, uncomfortable and time waste.
* code review
* download code and run `make test-dev` and `make test`.
* remove `lib.rs::mod example` and commit plz.

Test classify

---

Makefile
src/backtrace.rs
src/backtrace/stackframe_iter.rs
src/lib.rs
src/mm/page/os/metadata.rs
src/util/bitrange.rs
src/x86.rs

feat: per-cpu system descriptors

---

.cargo/config.toml
Cargo.lock
Makefile
kfs_macro/src/lib.rs
src/asm/interrupt.S
src/interrupt.rs
src/interrupt/apic/io.rs
src/interrupt/exception/generic.rs
src/interrupt/hw/apic_timer.rs
src/interrupt/hw/keyboard.rs
src/interrupt/idt.rs
src/lib.rs
src/process/context.rs
src/process/kthread.rs
src/process/user_space.rs
src/sync/cpu_local.rs
src/sync/lock.rs
src/sync/lock/spinlock.rs
src/sync/locked.rs
src/sync/singleton.rs
src/x86.rs

- InContext enum per cpu
- fn context_switch
- fn cpu_context
- context proc-macro

feat: InContext

---

Makefile
kfs_macro/src/lib.rs
src/config.rs
src/console.rs
src/console/console_manager.rs
src/driver/ps2.rs
src/driver/ps2/keyboard.rs
src/input/keyboard.rs
src/interrupt.rs
src/interrupt/hw/apic_timer.rs
src/interrupt/hw/keyboard.rs
src/interrupt/tasklet.rs
src/lib.rs
src/printk/printk.rs
src/process/context.rs
src/sync/cpu_local.rs
src/util.rs

- feat: tasklet
- feat: add InContext::PreemptDisabled
- feat: jiffies count per cpu
kstack size: rank 1 -> rank 10, before making a sensing system for stack overflow 
console tasklet: refactor later.

feat: tasklet

---

src/mm/alloc/page.rs
src/mm/alloc/phys/atomic.rs
src/mm/alloc/phys/normal.rs
src/sync/singleton.rs

To prevent suffering deadlock.

Temp: Alloc context

---

src/mm/alloc/virt.rs
src/mm/alloc/virt/kmap.rs
src/mm/alloc/virt/virtual_allocator.rs
src/mm/page.rs
src/mm/page/arch/directory.rs
src/mm/page/arch/init.rs
src/mm/page/arch/table.rs
src/mm/page/arch/util.rs
src/process/task.rs

- share kernel arbitrary mapping (VMALLOC / KMAP) among processes

feat: shared kernel mapping

---

src/file/read.rs
src/file/write.rs
src/interrupt/hw/apic_timer.rs
src/interrupt/interrupt_frame.rs
src/interrupt/syscall.rs
src/lib.rs
src/process.rs
src/process/fd_table.rs
src/process/task.rs

- fix: do signal in timer interrupt
- feat: sharable fd table

Sharable fd table

---

src/interrupt/exception.rs
src/interrupt/exception/generic.rs
src/interrupt/exception/page_fault.rs
src/mm/user/memory.rs
src/process/exit.rs
src/process/wait.rs
src/signal/sig_handler.rs
src/signal/sig_mask.rs
src/signal/sig_num.rs
userspace/include/kfs/kernel.h
userspace/init/init.c

current implementation: send SIGSEGV and exit
- resolves #53
- resolves #126

feat: user page-fault handler

---

src/interrupt/syscall.rs
src/process/relation/job.rs
src/process/relation/job/group.rs
src/process/relation/job/session.rs
src/process/task.rs
src/signal.rs
src/signal/kill.rs
userspace/include/kfs/kernel.h
userspace/init/init.c
userspace/libsystem/syscall.S

feat: sys_kill

---

src/interrupt/syscall.rs
src/process.rs
src/process/relation/id.rs
src/process/task.rs
src/process/uid.rs
src/signal/kill.rs
userspace/include/kfs/kernel.h
userspace/init/init.c
userspace/libsystem/syscall.S

- implement `getuid(2)`, `setuid(2)`
- resolves #128

process owner

---

Makefile
src/collection/line_buffer.rs
src/collection/wrap_queue.rs
src/console/ascii.rs
src/console/console_manager/console.rs
src/driver/tty.rs
src/lib.rs
src/mm/alloc/page/page_allocator.rs
src/mm/page/arch/table.rs
src/subroutine.rs
src/subroutine/dmesg.rs
src/subroutine/shell.rs

* use dynamically allocated buffer
* add i/o (read, write)
* add test

refactor: wrap_queue

---

src/console.rs
src/console/console_manager.rs
src/driver/tty.rs
src/interrupt/hw/keyboard.rs
src/lib.rs
src/process/task.rs
src/scheduler/sleep.rs
src/signal.rs
src/signal/sig_handler.rs
src/signal/sig_num.rs
src/user_bin.rs
userspace/Makefile
userspace/init/init.c
userspace/test_sig_stop_cont/Makefile
userspace/test_sig_stop_cont/test_sig_stop_cont.c

- feat: sigstop sigcont default action.
- test: sigcont sigstop.
- fix: drawing console screen when tty write.

feat: sigstop sigcont default action.

---

src/interrupt/exception/page_fault.rs
src/interrupt/syscall.rs
src/mm/page/arch/init.rs
src/mm/user.rs
src/mm/user/memory.rs
src/mm/user/mmap.rs
userspace/include/kfs/kernel.h
userspace/init/init.c
userspace/libsystem/syscall.S

feat: mmap (MMAP_PRIVATE only)

---

src/asm/interrupt.S
src/driver/serial.rs
src/interrupt/apic/io.rs
src/interrupt/idt.rs
src/lib.rs
src/printk/printk.rs
src/process/relation/id.rs
src/sync/lock/spinlock.rs

- feat: serial interrupt at runtime
- feat: serial ext
- feat: RUN_TIME global variable.
- feat: printk at runtime.

refactor: serial, printk

---

src/backtrace/stack_dump.rs
src/driver/pipe.rs
src/file.rs
src/file/close.rs
src/interrupt/syscall.rs
src/lib.rs
src/process/fd_table.rs
src/process/task.rs
src/user_bin.rs
userspace/Makefile
userspace/fortytwo/Makefile
userspace/fortytwo/main.c
userspace/include/kfs/kernel.h
userspace/init/init.c
userspace/libsystem/syscall.S
userspace/test_pipe/Makefile
userspace/test_pipe/test_pipe.c

* sys_close
* orphaned pipe handling (EOF / SIGPIPE)

feat: better pipe

---

.github/workflows/build-and-test.yml
Makefile
userspace/Makefile

* style check on push
* ktest on push

feat: github action

---

src/driver/bus/ata.rs
src/driver/ide.rs
src/driver/ide/block.rs
src/driver/ide/bmide.rs
src/driver/ide/dev_num.rs
src/driver/ide/lba.rs
src/driver/ide/partition.rs
src/driver/ide/prd.rs
src/interrupt.rs
src/lib.rs
src/printk/printk.rs
src/process/kthread.rs

refactor: `AtaController` 
fix: `Block` method for `?Sized`
feat:  kthread init
feat: `DevNum`
feat:  interface for getting `IDE AtaController`, `BMIDE`
feat: `LBA` byte_add
chore: split partition table lock.

refactor: ide hw interface

---

scripts/qemu.sh
src/fs.rs
src/fs/devfs.rs
src/fs/ext2/inode.rs
src/fs/path.rs
src/fs/procfs.rs
src/fs/syscall/close.rs
src/fs/syscall/cwd.rs
src/fs/syscall/open.rs
src/fs/tmpfs.rs
src/fs/vfs/entry.rs
src/fs/vfs/handle.rs
src/fs/vfs/inode.rs
src/fs/vfs/walk.rs
src/lib.rs
src/process/fd_table.rs
src/process/task.rs

- resolves #181 
new pseudo files:
- /proc/[PID]/cwd: current working directory of [PID]
- /proc/[PID]/fd/*: opened files of [PID]

feat: procfs

---

src/driver/apic/apic_timer.rs
src/driver/ide/dma/wait_io.rs
src/driver/serial.rs
src/driver/terminal/tty.rs
src/fs/syscall/read.rs
src/fs/syscall/write.rs
src/printk/printk.rs
src/process/signal.rs
src/process/task.rs
src/scheduler.rs
src/scheduler/context.rs
src/scheduler/preempt.rs
src/scheduler/sleep.rs
src/scheduler/work.rs
src/sync/lock_rw.rs
src/syscall/errno.rs
userspace/include/kfs/kernel.h

resolve #148 
- feat: preempt
- feat: schedule_worker
- fix: read, write syscall (len == 0)
- fix: lock_rw
- refactor: sleep_and_yield(task::state) -> sleep_and_yield(Sleep::*)

feat: preempt

---

src/fs/devfs.rs
src/fs/procfs.rs
src/fs/tmpfs.rs
src/fs/vfs/handle.rs
userspace/shell/shell.c

fix: KfsDirent

---

.cargo/config.toml
scripts/qemu.sh
src/driver/bus/ata.rs
src/fs/ext2/block_pool.rs
src/fs/ext2/constant.rs
src/fs/ext2/file.rs
src/fs/ext2/sb.rs
src/lib.rs
src/mm/alloc.rs
src/mm/alloc/cache.rs
src/mm/alloc/cache/cache_allocator.rs
src/mm/alloc/cache/cache_manager.rs
src/mm/alloc/cache/meta_cache.rs
src/mm/alloc/cache/no_alloc_list.rs
src/mm/alloc/cache/size_cache.rs
src/mm/alloc/cache/traits.rs
src/mm/alloc/phys/memory_allocator.rs
src/mm/constant.rs
src/mm/oom.rs
src/mm/page.rs
src/mm/page/os/table.rs
src/mm/util.rs
src/scheduler/work.rs

- fix: leak from cache allocator.
- refactor: cache allocator, alloc-dealloc O(N) -> O(1)
- test: oom handler thread

fix: leak from cache allocator

---

.cargo/config.toml
src/acpi.rs
src/acpi/fadt.rs
src/driver/ps2/control.rs
src/fs.rs
src/fs/ext2.rs
src/fs/ext2/sb.rs
src/lib.rs
src/syscall.rs
src/syscall/reboot.rs
userspace/getty/getty.c
userspace/include/kfs/kernel.h
userspace/include/unistd.h
userspace/shell/shell.c

- feat: reboot syscall
- shell: poweroff, reboot command
when you remove option of qemu `reboot=shutdown`, these features work correctly.

feat: reboot

---

scripts/hdd/make-hdd-linux.sh
scripts/hdd/make-sysroot.sh
userspace/getty/getty.c
userspace/shell/shell.c

env parser

---

.cargo/config.toml
Makefile
src/fs/vfs/entry.rs
src/fs/vfs/entry/file.rs
src/fs/vfs/handle.rs
src/fs/vfs/inode.rs
src/mm/alloc/page.rs
src/mm/alloc/page/buddy_allocator.rs
src/mm/alloc/phys.rs
src/mm/page/os/metadata.rs
src/mm/page/os/metapage.rs
src/mm/page/os/table.rs
src/mm/user/memory.rs
src/mm/user/memory/mapped_file.rs
src/mm/user/mmap.rs
src/mm/user/vma.rs
src/mm/util.rs
userspace/include/sys/mman.h
userspace/test/test.c
userspace/test_mmap/Makefile
userspace/test_mmap/test_mmap.c

feat: mmap shared

---

README.md

- move build informations in `README.md` to wiki `Build` page.

Refactor: README.md
